# Generated by Django 5.2 on 2025-05-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plant_name', models.CharField(blank=True, max_length=255)),
                ('care_instructions', models.TextField(blank=True)),
            ],
        ),
    ]
